### ISSUE TITLE
Cubeb for audio-speaker

### ISSUE THREAD

**Issue by jamen** [audiojs/node-cubeb#1]
Hello!

This addon is not ready yet, just backing up what I've done as I install Windows.

I'm revisiting `audio-speaker` with  [cubeb](https://github.com/kinetiknz/cubeb). I believe this should serve us better than mpg123:

- Cubeb's is on Git, while Mpg123 is on SVN.
- Cubeb is Firefox's audio backend, so basic support will be stronger.
- The Mpg123 binding involved autotools + GYP, which is a royal pain in the ass.
- Cubeb uses CMake. With [cmake-js](https://github.com/cmake-js/cmake-js) for the addon, its the smoothest experience I've had setting up.
- Cubeb's appears to support more functionality, such as loopback, naming the devices, and supports more audio backends (like Jack). Seems like better streaming API than Mpg123 too.

**Comment by jamen** [comment]
After trying to use `Napi::External` for a while, in both projects, with no success, I've decided to create classes using `Napi::ObjectWrap` instead:

- `Cubeb` A context
- `CubebStream`: An input or output stream

At first, [I made the stream params](https://github.com/audiojs/node-cubeb/blob/1e9ec65018879efc8580b67efcbdb557d26f3002/src/cubeb_binding.cc#L97) follow after [audio-format](https://github.com/audiojs/audio-format), but with all the attributes Cubeb already has, I think its more confusing and impractical to use audio-format instead of staying true to Cubeb's.

- `CUBEB_SAMPLE_*`: Sample formats (e.g. `CUBEB_SAMPLE_FLOAT32LE`)
- `CUBEB_LAYOUT_*`: Channel layouts (e.g. `CUBEB_LAYOUT_STEREO`)
- `CUBEB_STREAM_PREF_*`: Stream prefs (e.g. `CUBEB_STREAM_PREF_LOOPBACK`)
- `CUBEB_STATE_*`: Context states (e.g. `CUBEB_STATE_STARTED`)
- `CUBEB_DEVICE_TYPE_*`: Device types (e.g. `CUBEB_DEVICE_TYPE_OUTPUT`)
- `CUBEB_DEVICE_STATE_*` Device states (e.g. `CUBEB_DEVICE_STATE_UNPLUGGED`)
- `CUBEB_DEVICE_FMT_*`: Device formats (e.g. `CUBEB_DEVICE_FMT_S16LE`)
-  `CUBEB_DEVICE_PREF_*`: Device prefs (e.g. `CUBEB_DEVICE_PREF_MULTIMEDIA`)

**Comment by dy** [comment]
What packages may help you debug/develop that?
I can finish some if you need @jamen.

**Comment by jamen** [comment]
@dy I'm just learning how to use C++ still, so its been slow, but all the dependencies this package needs for testing are finished afaik.

To give an idea of what I'm aiming for, the package should work like this eventually:

```js
const { Cubeb } = require('cubeb')

// Create the context which manages streams and devices
const cubeb = new Cubeb("my-cubeb-context")

// Enumerate devices and select one.
for (const device of cubeb.enumerateDevices()) {
    console.log(device.friendly_name, device.max_channels, device.format)
}

// Create an output stream
const stream = cubeb.createStream(
    "my-output-stream",
    null, // input device and params are nulled to disable
    null,
    outputDevice,
    outputParams,
    latencyFrames,
    (input, output, suppliedFrames) => {
        // Use input buffer from a source stream
        input[...]
        // Use output buffer from a sink stream
        output[...] = ...
        // Indicate how many frames are consumed (i.e. were read or to be read).
        return consumedFrames
    },
    state => {
        // Check for state changes
        state === Cubeb.CUBEB_STATE_STARTED
    }
)
```

This more closely follows Cubeb's API, and its a pretty compact way of doing sink _and_ source streams.
